CARGOS = [
    'administrador de banco de dados',
    'administrador de dados',
    'administrador de infraestrutura',
    'administrador de redes',
    'administrador de sistemas',
    'analista de banco de dados',
    'analista de dados',
    'analista de desenvolvimento de sistemas',
    'analista de help desk',
    'analista de informática',
    'analista de infraestrutura',
    'analista de inteligência artificial',
    'analista de redes',
    'analista de segurança da informação',
    'analista de suporte',
    'analista de sistemas',
    'analista de tecnologia',
    'analista de ti',
    'analista de t.i.',
    'analista de testes',
    'analista em informática',
    'analista em tecnologia',
    'analista em ti',
    'analista em t.i.',
    'analista em geoprocessamento',
    'analista de geotecnologia',
    'analista forense digital',
    'análise de sistemas',
    'análise e desenvolvimento de sistemas',
    'arquiteto de dados',
    'arquiteto de infraestrutura',
    'arquiteto de software',
    'arquiteto de soluções',
    'arquiteto de sistemas',
    'arquiteto de tecnologia',
    'arquiteto de ti',
    'arquiteto de t.i.',
    'assistente de informática',
    'assistente de tecnologia',
    'assistente em ciência e tecnologia',
    'auditor de sistemas',
    'auditor de tecnologia',
    'auxiliar de informática',
    'auxiliar de tecnologia da informação',
    'ciência da computação',
    'ciências da computação',
    'cientista de dados',
    'computação forense',
    'desenvolvedor de aplicações',
    'desenvolvedor de programas',
    'desenvolvedor de sistemas',
    'desenvolvedor frontend',
    'desenvolvedor fullstack',
    'desenvolvedor web',
    'desenvolvedor backend',
    'desenvolvimento de sistemas',
    'digitalizador',
    'engenheiro de automação',
    'engenheiro de computação',
    'engenheiro da computação',
    'engenheiro de dados',
    'engenheiro de ia',
    'engenheiro de machine learning',
    'engenheiro de redes',
    'engenheiro de segurança da informação',
    'engenheiro de segurança de software',
    'engenheiro de software',
    'engenheiro de sistemas',
    'engenheiro de telecomunicações',
    'engenharia da computação',
    'engenharia de software',
    'especialista em banco de dados',
    'especialista em big data',
    'especialista em cybersegurança',
    'especialista em dados',
    'especialista em desenvolvimento',
    'especialista em gis',
    'especialista em governança de ti',
    'especialista em infraestrutura',
    'especialista em redes',
    'especialista em segurança cibernética',
    'especialista em segurança da informação',
    'especialista em sistemas',
    'especialista em suporte',
    'especialista em tecnologia da informação',
    'especialista em ti',
    'especialista em telecomunicações',
    'gestão de tecnologia da informação',
    'gestão da tecnologia da informação',
    'gestor de ti',
    'gestor de t.i.',
    'gestor de banco de dados',
    'infrastrutura de tecnologia da informação',
    'infraestrutura de redes',
    'instrutor de tecnologia da informação',
    'instrutor de ti',
    'manutenção de computadores',
    'matemática computacional',
    'matemática da computação',
    'operador de computador',
    'professional de informática',
    'professional de tecnologia da informação',
    'profissional de ti',
    'profissional de t.i.',
    'profissional de tecnologia',
    'professor de informática',
    'professor de tecnologia da informação',
    'programação de computadores',
    'programação de sistemas',
    'programador',
    'sistema da informação',
    'suporte de informática',
    'suporte de tecnologia',
    'suporte de ti',
    'suporte de t.i.',
    'suporte em sistemas',
    'suporte em informática',
    'suporte em tecnologia',
    'suporte em ti',
    'suporte em t.i.',
    'técnico de hardware',
    'técnico de informática',
    'técnico de redes',
    'técnico de segurança da informação',
    'técnico de software',
    'técnico de sistemas',
    'técnico de ti',
    'técnico de t.i.',
    'técnico em hardware',
    'técnico em informática',
    'técnico em redes',
    'técnico em software',
    'técnico em suporte',
    'técnico em tecnologia da informação',
    'técnico em ti',
    'técnico em t.i.',
    'técnico em telecomunicações',
    'tecnologia da informação e comunicação',
    'tecnologia de ti',
    'tecnologia de t.i.',
    'tecnologia em ti',
    'tecnologia em t.i.',
    'tecnólogo da informação',
    'tecnólogo de informática',
    'tecnólogo em informática',
    'tecnólogo de ti',
    'tecnólogo de t.i.',
    'tecnólogo em banco de dados',
    'tecnólogo em gestão da tecnologia da informação',
    'tecnólogo em redes de computadores',
    'tecnólogo em segurança da informação',
    'tecnólogo em sistemas para internet'
]