CARGOS = [
    'administrador de banco de dados',
    'administrador de dados',
    'administrador de infraestrutura',
    'administrador de redes',
    'administrador de sistemas',
    'analista de banco de dados',
    'analista de big data',
    'analista de bi',
    'analista de business intelligence',
    'analista de dados',
    'analista de devops',
    'analista de desenvolvimento de sistemas',
    'analista de governança',
    'analista de help desk',
    'analista de infraestrutura',
    'analista de inteligência artificial',
    'analista de negócios',
    'analista de processos de negócio',
    'analista de qualidade de software',
    'analista de redes',
    'analista de segurança da informação',
    'analista de suporte',
    'analista de sistemas',
    'analista de tecnologia da informação',
    'analista de testes',
    'analista de telecomunicações',
    'analista em tecnologia da informação',
    'analista em geoprocessamento',
    'analista de geotecnologia',
    'analista forense digital',
    'análise e desenvolvimento de sistemas',
    'arquiteto de dados',
    'arquiteto de infraestrutura',
    'arquiteto de software',
    'arquiteto de soluções',
    'arquiteto de sistemas',
    'arquiteto de tecnologia',
    'arquiteto de ti',
    'assistente de suporte de informática',
    'assistente de tecnologia da informação',
    'assistente em ciência e tecnologia',
    'auditor de sistemas',
    'auditor de ti',
    'auditor em tecnologia da informação',
    'cientista de dados',
    'ciência da computação',
    'computação forense',
    'desenvolvedor de aplicações',
    'desenvolvedor de programas',
    'desenvolvedor de sistemas',
    'desenvolvedor frontend',
    'desenvolvedor fullstack',
    'desenvolvedor web',
    'desenvolvedor backend',
    'digitalizador',
    'engenheiro de automação',
    'engenheiro de computação',
    'engenheiro da computação',
    'engenheiro de dados',
    'engenheiro de ia',
    'engenheiro de machine learning',
    'engenheiro de redes',
    'engenheiro de segurança da informação',
    'engenheiro de segurança de software',
    'engenheiro de software',
    'engenheiro de sistemas',
    'engenheiro de telecomunicações',
    'engenharia da computação',
    'engenharia de software',
    'especialista em big data',
    'especialista em cybersegurança',
    'especialista em dados',
    'especialista em desenvolvimento',
    'especialista em gis',
    'especialista em governança de ti',
    'especialista em infraestrutura',
    'especialista em redes',
    'especialista em segurança cibernética',
    'especialista em segurança da informação',
    'especialista em sistemas',
    'especialista em suporte',
    'especialista em tecnologia da informação',
    'especialista em telecomunicações',
    'gestão de tecnologia da informação',
    'gestão de tecnologia de informação',
    'instrutor de informática',
    'informática forense',
    'monitor de informática',
    'operador de computador',
    'operador de sistemas',
    'profissional de ti',
    'profissional de tecnologia',
    'programador',
    'rede de computadores',
    'redes de computadores',
    'supervisor de informática',
    'técnico de hardware',
    'técnico de informática',
    'técnico de laboratório de informática',
    'técnico de redes',
    'técnico de segurança da informação',
    'técnico de software',
    'técnico de sistemas',
    'técnico em desenvolvimento',
    'técnico em hardware',
    'técnico em informática',
    'técnico em software',
    'técnico em suporte',
    'técnico em tecnologia da informação',
    'técnico em telecomunicações',
    'tecnólogo da informação',
    'tecnólogo em análise e desenvolvimento de sistemas',
    'tecnólogo em banco de dados',
    'tecnólogo em gestão da tecnologia da informação',
    'tecnólogo em redes de computadores',
    'tecnólogo em segurança da informação',
    'tecnólogo em sistemas para internet'
]